name: Attach Assets
on:
  release:
    types:
      - created
env:
  name: solarman
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Zip
      run: |
          cd ${{ github.workspace }}/custom_components/$name
          sed -i "s/0\.0\.0/$(echo '${{ github.event.release.name }}' | cut -c 2-)/g" manifest.json
          cp ../../license ./
          zip -r ../$name.zip . -x "*.git*" "*.git/*" "*.github/*"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/custom_components/*.zip
