name: Attach Assets
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Zip
      run: |
          cd ${{ github.workspace }}/custom_components/solarman
          zip -r solarman.zip . -x ".git/*" ".github/*" ".gitignore" ".gitmodules"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/custom_components/solarman/solarman.zip